-- Migration: 0003_duration
-- Track API call duration in call_logs
-- NOTE: This column is managed by db.ts runtime migration (ALTER TABLE with try/catch).
-- The migration file exists as a marker only.
