-- Migration: 0004_rate_limits_banned_until
-- Add banned_until column to rate_limits table (missing from 0001_init.sql schema)
-- NOTE: This column is managed by db.ts runtime migration (ALTER TABLE with try/catch).
-- The migration file exists as a marker only.
